# Cloud Build Configuration for CareLink Web Client
# ใช้ gcloud builds submit --config=cloudbuild.yaml เพื่อทำการ build

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.gcp'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$BUILD_ID'
      - '.'
    dir: 'web-client'

  # Step 2: Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest'
    dir: 'web-client'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image-sha'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA'
    dir: 'web-client'
    waitFor: ['build-image']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=.
      - --image=gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest
      - --location=$_REGION
      - --output=/workspace/deploy
    dir: 'web-client'
    waitFor: ['push-image']

  # Step 4: Deploy using gcloud CLI
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-cloud-run'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - '$_REGION'
      - '--port'
      - '8080'
      - '--memory'
      - '$_MEMORY'
      - '--cpu'
      - '$_CPU'
      - '--max-instances'
      - '$_MAX_INSTANCES'
      - '--min-instances'
      - '$_MIN_INSTANCES'
      - '--timeout'
      - '3600'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'REACT_APP_API_URL=$_API_URL'
      - '--labels'
      - 'env=$_ENVIRONMENT,app=carelink-web-client,built-by=cloud-build'
    waitFor: ['push-image']

# Image names for artifacts
images:
  - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest'
  - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$BUILD_ID'

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

# Timeout for the entire build
timeout: '1800s'

# Substitutions - can be overridden via --substitutions flag
substitutions:
  _IMAGE_NAME: 'web-client'
  _SERVICE_NAME: 'carelink-web-client'
  _REGION: 'asia-southeast1'
  _ENVIRONMENT: 'production'
  _MEMORY: '512Mi'
  _CPU: '1'
  _MAX_INSTANCES: '100'
  _MIN_INSTANCES: '1'
  _API_URL: 'https://carelink-strapi-xxxxx.run.app'

# Step-by-step breakdown:
# 1. Build: ใช้ Node 18 Alpine image เพื่อสร้าง React app
# 2. Push: ส่ง image ไปยัง Container Registry
# 3. Deploy: Deploy ไป Cloud Run ด้วยตั้งค่า production

# Usage:
# gcloud builds submit --config=cloudbuild.yaml \
#   --substitutions _IMAGE_NAME=web-client,_SERVICE_NAME=carelink-web-client,_API_URL=https://carelink-strapi-xxxxx.run.app
