# cloudbuild.yaml สำหรับ Web Client
steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest'
      - '.' # รันจากตำแหน่งปัจจุบันที่ส่งไฟล์ขึ้นไป

  # Step 2: Push image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-cloud-run'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'REACT_APP_API_URL=$_API_URL'
    waitFor: ['push-image']

substitutions:
  _IMAGE_NAME: 'web-client'
  _SERVICE_NAME: 'carelink-web-client'
  _REGION: 'asia-southeast1'
  _API_URL: 'https://carelink-strapi-ke4rorabaa-as.a.run.app'

options:
  logging: CLOUD_LOGGING_ONLY